// Расширенные данные зикров для приложения
// Источник: https://bot.e-replika.ru/docs

import type { DhikrItem } from "./dhikr-data";

// ═══════════════════════════════════════════════════════════════
// ДУААТЫ (Мольбы) - расширенный список по категориям
// ═══════════════════════════════════════════════════════════════

export const EXTENDED_DUAS: DhikrItem[] = [
  // ═══════════════════════════════════════════════════════════════
  // УТРЕННИЕ ДУА
  // ═══════════════════════════════════════════════════════════════
  {
    id: "morning-1",
    arabic: "اللَّهُمَّ أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ",
    transcription: "Allahumma asbahna wa asbaha al-mulku lillahi wal-hamdu lillah",
    russianTranscription: "Аллахумма асбахна ва асбаха аль-мульку лиллях валь-хамду лиллях",
    translation: "О Аллах, мы встретили утро, и вся власть и хвала принадлежат Аллаху",
    reference: "Сахих Муслим",
    category: "morning",
    count: 1,
  },
  {
    id: "morning-2",
    arabic: "أَصْبَحْنَا عَلَى فِطْرَةِ الْإِسْلَامِ وَعَلَى كَلِمَةِ الْإِخْلَاصِ وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ ﷺ وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ",
    transcription: "Asbahna ala fitratil-Islam wa ala kalimatil-ikhlas wa ala dini nabiyyina Muhammad ﷺ wa ala millati abina Ibrahim hanifan musliman wa ma kana minal-mushrikin",
    russianTranscription: "Асбахна аля фитратиль-Ислям ва аля калиматиль-ихляс ва аля дини набийина Мухаммадин ﷺ ва аля миллати абина Ибрахима ханифан муслиман ва ма кана миналь-мушрикин",
    translation: "Мы встретили утро на естестве Ислама, на слове искренности, на религии нашего Пророка Мухаммада ﷺ, и на вере отца нашего Ибрахима, который был ханифом, мусульманином и не был из многобожников",
    reference: "Муснад Ахмад",
    category: "morning",
    count: 1,
  },
  {
    id: "morning-3",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ وَهُدَاهُ وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهِ وَشَرِّ مَا بَعْدَهُ",
    transcription: "Allahumma inni as'aluka khayra hadhal-yawmi fathahu wa nasrahu wa nurahu wa barakatahu wa hudahu wa a'udhu bika min sharri ma fihi wa sharri ma ba'dah",
    russianTranscription: "Аллахумма инни асъалюка хайра хазаль-йауми фатхаху ва насраху ва нураху ва баракатаху ва худаху ва аузу бика мин шарри ма фиихи ва шарри ма баъдах",
    translation: "О Аллах, я прошу Тебя о благе этого дня: его победе, помощи, свете, благодати и руководстве. И я прибегаю к Тебе от зла того, что в нём, и от зла того, что после него",
    reference: "Абу Дауд",
    category: "morning",
    count: 1,
  },
  {
    id: "morning-4",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transcription: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan-nushur",
    russianTranscription: "Аллахумма бика асбахна ва бика амсайна ва бика нахья ва бика намуту ва иляйкан-нушур",
    translation: "О Аллах, с Твоей помощью мы встретили утро и вечер, с Тобой живём и умираем, и к Тебе воскресение",
    reference: "Тирмизи",
    category: "morning",
    count: 1,
  },
  {
    id: "morning-5",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لَا إِلَهَ إِلَّا أَنْتَ",
    transcription: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa Ant",
    russianTranscription: "Аллахумма афини фи бадани, Аллахумма афини фи самъи, Аллахумма афини фи басари, ля иляха илля Ант",
    translation: "О Аллах, дай благополучие моему телу. О Аллах, дай благополучие моему слуху. О Аллах, дай благополучие моему зрению. Нет божества, кроме Тебя",
    reference: "Абу Дауд. Читать 3 раза",
    category: "morning",
    count: 3,
  },
  {
    id: "morning-6",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ لَا إِلَهَ إِلَّا أَنْتَ",
    transcription: "Allahumma inni a'udhu bika minal-kufri wal-faqri wa a'udhu bika min 'adhabil-qabri la ilaha illa Ant",
    russianTranscription: "Аллахумма инни аузу бика миналь-куфри валь-факри ва аузу бика мин азабиль-кабри ля иляха илля Ант",
    translation: "О Аллах, я прибегаю к Тебе от неверия и бедности, и прибегаю к Тебе от мучений могилы. Нет божества, кроме Тебя",
    reference: "Абу Дауд. Читать 3 раза",
    category: "morning",
    count: 3,
  },
  {
    id: "morning-7",
    arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
    transcription: "Ya Hayyu Ya Qayyum birahmatika astaghith aslih li sha'ni kullahu wa la takilni ila nafsi tarfata 'ayn",
    russianTranscription: "Йа Хаййю Йа Каййюм бирахматика астагис аслих ли шаъни кулляху ва ля такильни иля нафси тарфата айн",
    translation: "О Живой, о Вечный! К Твоей милости взываю о помощи. Исправь всё моё положение и не оставляй меня с самим собой даже на мгновение ока",
    reference: "Аль-Хаким",
    category: "morning",
    count: 1,
  },
  {
    id: "morning-8",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
    transcription: "Raditu billahi Rabban wa bil-Islami dinan wa bi-Muhammadin ﷺ nabiyya",
    russianTranscription: "Радыту биллляхи Раббан ва биль-Исляями динан ва бимухаммадин ﷺ набиййа",
    translation: "Я доволен Аллахом как Господом, Исламом как религией и Мухаммадом ﷺ как пророком",
    reference: "Абу Дауд. Читать 3 раза — будет право на заступничество",
    category: "morning",
    count: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // ВЕЧЕРНИЕ ДУА
  // ═══════════════════════════════════════════════════════════════
  {
    id: "evening-1",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    transcription: "Amsayna wa amsal-mulku lillahi wal-hamdu lillah la ilaha illallahu wahdahu la sharika lah",
    russianTranscription: "Амсайна ва амсаль-мульку лиллях валь-хамду лиллях ля иляха илляллаху вахдаху ля шарика лях",
    translation: "Мы встретили вечер, и вся власть и хвала принадлежат Аллаху. Нет божества, кроме Аллаха Единого, у Которого нет сотоварища",
    reference: "Сахих Муслим",
    category: "evening",
    count: 1,
  },
  {
    id: "evening-2",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transcription: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal-masir",
    russianTranscription: "Аллахумма бика амсайна ва бика асбахна ва бика нахья ва бика намуту ва иляйкаль-масыр",
    translation: "О Аллах, с Твоей помощью мы встретили вечер и утро, с Тобой живём и умираем, и к Тебе возвращение",
    reference: "Тирмизи",
    category: "evening",
    count: 1,
  },
  {
    id: "evening-3",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ مَا خَلَقْتَ",
    transcription: "Allahumma inni a'udhu bika min sharri ma khalaqt",
    russianTranscription: "Аллахумма инни аузу бика мин шарри ма халякт",
    translation: "О Аллах, я прибегаю к Тебе от зла того, что Ты сотворил",
    reference: "Сахих Муслим. Читать 3 раза",
    category: "evening",
    count: 3,
  },
  {
    id: "evening-4",
    arabic: "أَمْسَيْنَا عَلَى فِطْرَةِ الْإِسْلَامِ وَعَلَى كَلِمَةِ الْإِخْلَاصِ وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ ﷺ",
    transcription: "Amsayna ala fitratil-Islam wa ala kalimatil-ikhlas wa ala dini nabiyyina Muhammad ﷺ",
    russianTranscription: "Амсайна аля фитратиль-Ислям ва аля калиматиль-ихляс ва аля дини набийина Мухаммад ﷺ",
    translation: "Мы встретили вечер на естестве Ислама, на слове искренности и на религии нашего Пророка Мухаммада ﷺ",
    reference: "Муснад Ахмад",
    category: "evening",
    count: 1,
  },
  {
    id: "evening-5",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا فِيهَا وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا فِيهَا",
    transcription: "Allahumma inni as'aluka khayra hadhihil-laylati wa khayra ma fiha wa a'udhu bika min sharriha wa sharri ma fiha",
    russianTranscription: "Аллахумма инни асъалюка хайра хазихиль-ляйляти ва хайра ма фииха ва аузу бика мин шарриха ва шарри ма фииха",
    translation: "О Аллах, я прошу Тебя о благе этой ночи и благе того, что в ней, и прибегаю к Тебе от её зла и от зла того, что в ней",
    reference: "Абу Дауд",
    category: "evening",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ПЕРЕД СНОМ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sleep-1",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transcription: "Bismika Allahumma amutu wa ahya",
    russianTranscription: "Бисмика Аллахумма амуту ва ахья",
    translation: "С именем Твоим, О Аллах, я умираю и оживаю",
    reference: "Сахих аль-Бухари",
    category: "sleep",
    count: 1,
  },
  {
    id: "sleep-2",
    arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    transcription: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
    russianTranscription: "Аллахумма кыни азабака йауыма табасу ибадак",
    translation: "О Аллах, защити меня от Твоего наказания в День, когда Ты воскресишь Своих рабов",
    reference: "Абу Дауд. Читать 3 раза",
    category: "sleep",
    count: 3,
  },
  {
    id: "sleep-3",
    arabic: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ وَوَجَّهْتُ وَجْهِي إِلَيْكَ وَفَوَّضْتُ أَمْرِي إِلَيْكَ وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ رَغْبَةً وَرَهْبَةً إِلَيْكَ لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ",
    transcription: "Allahumma aslamtu nafsi ilayka wa wajjahtu wajhi ilayka wa fawwadtu amri ilayka wa alja'tu zahri ilayka raghbatan wa rahbatan ilayka la malja'a wa la manja minka illa ilayka amantu bikitabikal-ladhi anzalta wa binabiyyikal-ladhi arsalt",
    russianTranscription: "Аллахумма аслямту нафси иляйка ва ваджахту ваджхи иляйка ва фаввадту амри иляйка ва альджаъту захри иляйка рагбатан ва рахбатан иляйка ля мальджаа ва ля манджа минка илля иляйка аманту бикитабикаль-лязи анзальта ва бинабийикаль-лязи арсальт",
    translation: "О Аллах, я предал себя Тебе, обратил лицо к Тебе, поручил дела Тебе и обратил спину к Тебе в надежде и страхе перед Тобой. Нет убежища и спасения от Тебя, кроме как к Тебе. Я уверовал в Книгу, которую Ты ниспослал, и в Пророка, которого Ты отправил",
    reference: "Сахих Бухари. Если умрёшь той ночью — умрёшь на фитре",
    category: "sleep",
    count: 1,
  },
  {
    id: "sleep-4",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَكَفَانَا وَآوَانَا فَكَمْ مِمَّنْ لَا كَافِيَ لَهُ وَلَا مُؤْوِيَ",
    transcription: "Alhamdulillahil-ladhi at'amana wa saqana wa kafana wa awana fakam mimman la kafiya lahu wa la mu'wiy",
    russianTranscription: "Альхамдулилляхиль-лязи атъамана ва сакана ва кафана ва авана факам мимман ля кафия ляху ва ля муъви",
    translation: "Хвала Аллаху, Который накормил нас, напоил, избавил от нужды и дал пристанище. Сколько тех, у кого нет ни защитника, ни приюта",
    reference: "Сахих Муслим",
    category: "sleep",
    count: 1,
  },
  {
    id: "sleep-5",
    arabic: "اللَّهُمَّ رَبَّ السَّمَوَاتِ وَرَبَّ الْأَرْضِ وَرَبَّ الْعَرْشِ الْعَظِيمِ رَبَّنَا وَرَبَّ كُلِّ شَيْءٍ فَالِقَ الْحَبِّ وَالنَّوَى وَمُنْزِلَ التَّوْرَاةِ وَالْإِنْجِيلِ وَالْفُرْقَانِ أَعُوذُ بِكَ مِنْ شَرِّ كُلِّ شَيْءٍ أَنْتَ آخِذٌ بِنَاصِيَتِهِ",
    transcription: "Allahumma Rabbas-samawati wa Rabbal-ardi wa Rabbal-'Arshil-'Adhim Rabbana wa Rabba kulli shay'in faliqal-habbi wan-nawa wa munzilat-Tawrati wal-Injili wal-Furqani a'udhu bika min sharri kulli shay'in Anta akhidhun binasiyatih",
    russianTranscription: "Аллахумма Раббас-самавати ва Раббаль-арды ва Раббаль-Аршиль-Азым Раббана ва Рабба кулли шайин фаликаль-хабби ван-нава ва мунзилят-Тавраати валь-Инджили валь-Фуркани аузу бика мин шарри кулли шайин Анта ахизун бинасыятих",
    translation: "О Аллах, Господь небес, Господь земли, Господь Великого Трона, наш Господь и Господь всякой вещи! Раскалывающий зёрна и косточки, ниспославший Тору, Евангелие и Различение! Прибегаю к Тебе от зла всякой вещи, за чуб которой Ты держишь",
    reference: "Сахих Муслим",
    category: "sleep",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ЗАЩИТА
  // ═══════════════════════════════════════════════════════════════
  {
    id: "protection-1",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transcription: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    russianTranscription: "Аузу бикалиматиллях ат-таммати мин шарри ма халяк",
    translation: "Прибегаю к совершенным словам Аллаха от зла того, что Он сотворил",
    reference: "Сахих Муслим. Читать 3 раза — защита от укуса",
    category: "protection",
    count: 3,
  },
  {
    id: "protection-2",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transcription: "Bismillahil-ladhi la yadurru ma'a ismihi shay'un fil-ardi wa la fis-sama'i wa huwas-Sami'ul-'Alim",
    russianTranscription: "Бисмилляхиль-лязи ля ядурру маа исмихи шайун филь-арды ва ля фис-самаи ва хувас-Самиуль-Алим",
    translation: "С именем Аллаха, с именем Которого ничто не причинит вреда ни на земле, ни на небе. Он — Слышащий, Знающий",
    reference: "Абу Дауд. Читать 3 раза — ничто не навредит в тот день",
    category: "protection",
    count: 3,
  },
  {
    id: "protection-3",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    transcription: "Allahumma inni a'udhu bika minal-hammi wal-hazani wal-'ajzi wal-kasali wal-bukhli wal-jubni wa dala'id-dayni wa ghalabatir-rijal",
    russianTranscription: "Аллахумма инни аузу бика миналь-хамми валь-хазани валь-аджзи валь-касали валь-бухли валь-джубни ва даляид-дайни ва галябатир-риджаль",
    translation: "О Аллах, я прибегаю к Тебе от беспокойства и печали, от слабости и лени, от скупости и трусости, от бремени долга и притеснения людей",
    reference: "Сахих аль-Бухари",
    category: "protection",
    count: 1,
  },
  {
    id: "protection-4",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْبَرَصِ وَالْجُنُونِ وَالْجُذَامِ وَمِنْ سَيِّئِ الْأَسْقَامِ",
    transcription: "Allahumma inni a'udhu bika minal-barasi wal-jununi wal-judhami wa min sayyi'il-asqam",
    russianTranscription: "Аллахумма инни аузу бика миналь-бараси валь-джунуни валь-джузами ва мин сайиъиль-аскам",
    translation: "О Аллах, я прибегаю к Тебе от проказы, безумия, слоновой болезни и тяжёлых недугов",
    reference: "Абу Дауд",
    category: "protection",
    count: 1,
  },
  {
    id: "protection-5",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ وَتَحَوُّلِ عَافِيَتِكَ وَفُجَاءَةِ نِقْمَتِكَ وَجَمِيعِ سَخَطِكَ",
    transcription: "Allahumma inni a'udhu bika min zawali ni'matika wa tahawwuli 'afiyatika wa fuja'ati niqmatika wa jami'i sakhatik",
    russianTranscription: "Аллахумма инни аузу бика мин завали ниъматика ва тахаввули афиятика ва фуджааати никматика ва джамии сахатик",
    translation: "О Аллах, я прибегаю к Тебе от исчезновения Твоей милости, от изменения Твоей защиты, от внезапности Твоего наказания и от всего Твоего гнева",
    reference: "Сахих Муслим",
    category: "protection",
    count: 1,
  },
  {
    id: "protection-6",
    arabic: "اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي",
    transcription: "Allahumma-hfadhni min bayni yadayya wa min khalfi wa 'an yamini wa 'an shimali wa min fawqi wa a'udhu bi'adhamatika an ughtala min tahti",
    russianTranscription: "Аллахумма-хфазни мин байни ядаййа ва мин хальфи ва ан йамини ва ан шимали ва мин фауки ва аузу биазаматика ан угтала мин тахти",
    translation: "О Аллах, защити меня спереди и сзади, справа и слева, и сверху. И прибегаю к Твоему величию от того, чтобы быть погублённым снизу",
    reference: "Абу Дауд",
    category: "protection",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ПОКАЯНИЕ И ПРОЩЕНИЕ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "repentance-1",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transcription: "Astaghfirullaha al-'Adhima alladhi la ilaha illa Huwal-Hayyul-Qayyumu wa atubu ilayh",
    russianTranscription: "Астагфируллахаль-Азыма аллязи ля иляха илля хуваль-Хаййюль-Каййюму ва атубу иляйх",
    translation: "Прошу прощения у Великого Аллаха, кроме Которого нет божества, Живого, Вечного, и каюсь перед Ним",
    reference: "Абу Дауд. Прощаются грехи, даже если бежал с поля боя",
    category: "repentance",
    count: 3,
  },
  {
    id: "repentance-2",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transcription: "Allahumma anta Rabbi la ilaha illa anta khalaqtani wa ana 'abduka wa ana 'ala 'ahdika wa wa'dika mastata't a'udhu bika min sharri ma sana't abu'u laka bini'matika 'alayya wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant",
    russianTranscription: "Аллахумма анта Рабби ля иляха илля анта халяктани ва ана абдука ва ана аля ахдика ва ваъдика мастатаът аузу бика мин шарри ма санаът абуу ляка биниъматика аляййа ва абуу бизанби фагфир ли фа иннаху ля ягфиру з-зунуба илля ант",
    translation: "О Аллах, Ты — мой Господь, нет божества, кроме Тебя. Ты создал меня, и я — Твой раб. Я верен завету с Тобой и обещанию, насколько могу. Прибегаю к Тебе от зла того, что совершил. Признаю Твою милость ко мне и признаю свой грех. Прости меня, ведь никто не прощает грехи, кроме Тебя",
    reference: "Сайид аль-Истигфар. Сахих Бухари. Господин истигфара",
    category: "repentance",
    count: 1,
  },
  {
    id: "repentance-3",
    arabic: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    transcription: "Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasirin",
    russianTranscription: "Раббана залямна анфусана ва ин лям тагфир ляна ва тархамна лянакунанна миналь-хасирин",
    translation: "Господь наш! Мы сами себе причинили зло. Если Ты не простишь нас и не помилуешь, мы непременно окажемся в числе потерпевших убыток",
    reference: "Дуа Адама. Коран 7:23",
    category: "repentance",
    count: 3,
  },
  {
    id: "repentance-4",
    arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
    transcription: "Rabbighfir li wa tub 'alayya innaka antat-Tawwabur-Rahim",
    russianTranscription: "Раббигфир ли ва туб аляййа иннака антат-Таввабур-Рахим",
    translation: "Господи, прости меня и прими моё покаяние. Воистину, Ты — Принимающий покаяние, Милосердный",
    reference: "Абу Дауд, Тирмизи. Читать 100 раз в день",
    category: "repentance",
    count: 100,
  },
  {
    id: "repentance-5",
    arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ دِقَّهُ وَجِلَّهُ وَأَوَّلَهُ وَآخِرَهُ وَعَلَانِيَتَهُ وَسِرَّهُ",
    transcription: "Allahumma-ghfir li dhanbi kullahu diqqahu wa jillahu wa awwalahu wa akhirahu wa 'alaniyatahu wa sirrahu",
    russianTranscription: "Аллахумма-гфир ли занби кулляху диккаху ва джилляху ва авваляху ва ахираху ва алянийатаху ва сирраху",
    translation: "О Аллах, прости мне все мои грехи: малые и большие, первые и последние, явные и тайные",
    reference: "Сахих Муслим",
    category: "repentance",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // БЛАГОДАРНОСТЬ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "gratitude-1",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَكَفَانَا وَآوَانَا",
    transcription: "Alhamdulillahil-ladhi at'amana wa saqana wa kafana wa awana",
    russianTranscription: "Альхамдулилляхиль-лязи атъамана ва сакана ва кафана ва авана",
    translation: "Хвала Аллаху, Который накормил нас, напоил, избавил от нужды и дал пристанище",
    reference: "Сахих Муслим",
    category: "gratitude",
    count: 1,
  },
  {
    id: "gratitude-2",
    arabic: "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
    transcription: "Allahumma ma asbaha bi min ni'matin aw bi-ahadin min khalqika faminka wahdaka la sharika laka falakal-hamdu wa lakash-shukr",
    russianTranscription: "Аллахумма ма асбаха би мин ниъматин ау биахадин мин халькика фаминка вахдака ля шарика ляка фалякаль-хамду ва лякаш-шукр",
    translation: "О Аллах, какая бы милость не была мне дарована или любому из Твоих творений, она только от Тебя одного, у Которого нет сотоварища. Тебе хвала и благодарность",
    reference: "Абу Дауд. Кто скажет утром — выполнит благодарность дня",
    category: "gratitude",
  },
  {
    id: "gratitude-3",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transcription: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    russianTranscription: "Аллахумма аинни аля зикрика ва шукрика ва хусни ибадатик",
    translation: "О Аллах, помоги мне поминать Тебя, благодарить Тебя и наилучшим образом поклоняться Тебе",
    reference: "Абу Дауд. Завет Пророка ﷺ Муазу",
    category: "gratitude",
    count: 1,
  },
  {
    id: "gratitude-4",
    arabic: "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ",
    transcription: "Alhamdulillahi 'ala kulli hal",
    russianTranscription: "Альхамдулилляхи аля кулли халь",
    translation: "Хвала Аллаху при любом положении",
    reference: "При неприятности",
    category: "gratitude",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ЗДОРОВЬЕ И ИСЦЕЛЕНИЕ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "health-1",
    arabic: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِهِ وَأَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا",
    transcription: "Allahumma Rabban-nas adhhib il-ba's ishfihi wa Antash-Shafi la shifa'a illa shifa'uka shifa'an la yughadiru saqama",
    russianTranscription: "Аллахумма Раббан-нас азхибиль-баъс ишфихи ва Анташ-Шафи ля шифааа илля шифаука шифааан ля йугадиру сакама",
    translation: "О Аллах, Господь людей! Удали болезнь, исцели его, ведь Ты — Исцеляющий. Нет исцеления, кроме Твоего исцеления. Исцели так, чтобы не осталось болезни",
    reference: "Сахих Бухари",
    category: "health",
    count: 3,
  },
  {
    id: "health-2",
    arabic: "بِسْمِ اللَّهِ أَرْقِيكَ مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ اللَّهُ يَشْفِيكَ بِسْمِ اللَّهِ أَرْقِيكَ",
    transcription: "Bismillahi arqika min kulli shay'in yu'dhika min sharri kulli nafsin aw 'ayni hasidin Allahu yashfika bismillahi arqik",
    russianTranscription: "Бисмилляхи аркика мин кулли шайин йузика мин шарри кулли нафсин ау айни хасидин Аллаху йашфика бисмилляхи аркик",
    translation: "С именем Аллаха заклинаю тебя от всего, что тебе вредит, от зла каждой души и завистливого глаза. Аллах исцелит тебя, с именем Аллаха заклинаю тебя",
    reference: "Сахих Муслим. Рукья от всех болезней",
    category: "health",
    count: 3,
  },
  {
    id: "health-3",
    arabic: "أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ",
    transcription: "As'alullaha al-'Adhima Rabbal-'Arshil-'Adhimi an yashfiyak",
    russianTranscription: "Асъалюллахаль-Азыма Раббаль-Аршиль-Азыми ан йашфияк",
    translation: "Прошу Великого Аллаха, Господа Великого Трона, чтобы Он исцелил тебя",
    reference: "Тирмизи. Читать 7 раз — исцелится, если не суждена смерть",
    category: "health",
    count: 7,
  },
  {
    id: "health-4",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    transcription: "Allahumma 'afini fi badani Allahumma 'afini fi sam'i Allahumma 'afini fi basari",
    russianTranscription: "Аллахумма афини фи бадани Аллахумма афини фи самъи Аллахумма афини фи басари",
    translation: "О Аллах, дай благополучие моему телу. О Аллах, дай благополучие моему слуху. О Аллах, дай благополучие моему зрению",
    reference: "Абу Дауд",
    category: "health",
    count: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // РИЗК И БОГАТСТВО
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rizq-1",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
    transcription: "Allahumma inni as'aluka 'ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbala",
    russianTranscription: "Аллахумма инни асъалюка ильман нафиан ва ризкан таййибан ва амалян мутакаббаля",
    translation: "О Аллах, я прошу Тебя полезного знания, благого удела и принятых деяний",
    reference: "Ибн Маджа. Читать утром",
    category: "rizq",
    count: 1,
  },
  {
    id: "rizq-2",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transcription: "Allahummak-fini bihalalika 'an haramika wa aghnini bifadlika 'amman siwak",
    russianTranscription: "Аллахуммак-фини бихалялика ан харамика ва агнини бифадлика амман сивак",
    translation: "О Аллах, избавь меня Твоим дозволенным от запретного и обогати меня Твоей милостью от нужды в ком-либо, кроме Тебя",
    reference: "Тирмизи. При долгах и бедности",
    category: "rizq",
    count: 1,
  },
  {
    id: "rizq-3",
    arabic: "اللَّهُمَّ رَبَّ السَّمَوَاتِ السَّبْعِ وَرَبَّ الْعَرْشِ الْعَظِيمِ اقْضِ عَنِّي الدَّيْنَ وَأَغْنِنِي مِنَ الْفَقْرِ",
    transcription: "Allahumma Rabbas-samawatis-sab'i wa Rabbal-'Arshil-'Adhim iqdi 'anid-dayna wa aghnini minal-faqr",
    russianTranscription: "Аллахумма Раббас-самаватис-сабъи ва Раббаль-Аршиль-Азым икды анид-дайна ва агнини миналь-факр",
    translation: "О Аллах, Господь семи небес и Великого Трона! Избавь меня от долга и защити от бедности",
    reference: "Аль-Хаким",
    category: "rizq",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // СЕМЬЯ И БРАК
  // ═══════════════════════════════════════════════════════════════
  {
    id: "family-1",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transcription: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    russianTranscription: "Раббана хаб ляна мин азваджина ва зурриййатина курра та аъйунин ваджъальна лиль-муттакина имама",
    translation: "Господь наш! Даруй нам от наших жён и потомков отраду глаз и сделай нас образцом для богобоязненных",
    reference: "Коран 25:74",
    category: "family",
    count: 1,
  },
  {
    id: "family-2",
    arabic: "رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً إِنَّكَ سَمِيعُ الدُّعَاءِ",
    transcription: "Rabbi hab li min ladunka dhurriyyatan tayyibatan innaka Sami'ud-du'a",
    russianTranscription: "Рабби хаб ли мин лядунка зурриййатан таййибатан иннака Самиуд-дуаа",
    translation: "Господи! Даруй мне от Себя благое потомство. Воистину, Ты — Слышащий мольбу",
    reference: "Дуа Закарии. Коран 3:38",
    category: "family",
    count: 1,
  },
  {
    id: "family-3",
    arabic: "اللَّهُمَّ بَارِكْ لَهُمَا وَبَارِكْ عَلَيْهِمَا وَاجْمَعْ بَيْنَهُمَا فِي خَيْرٍ",
    transcription: "Allahumma barik lahuma wa barik 'alayhima wajma' baynahuma fi khayr",
    russianTranscription: "Аллахумма барик ляхума ва барик аляйхима ваджмаъ байнахума фи хайр",
    translation: "О Аллах, благослови их обоих и ниспошли им благословение, и соедини их в благе",
    reference: "Абу Дауд. Дуа для молодожёнов",
    category: "family",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ДЕТИ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "children-1",
    arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
    transcription: "Rabbij'alni muqimas-salati wa min dhurriyyati Rabbana wa taqabbal du'a",
    russianTranscription: "Раббидж'альни мукимас-саляати ва мин зурриййяти Раббана ва такаббаль дуаа",
    translation: "Господи! Сделай меня и часть моего потомства выстаивающими намаз. Господь наш, прими мою мольбу",
    reference: "Дуа Ибрахима. Коран 14:40",
    category: "children",
    count: 1,
  },
  {
    id: "children-2",
    arabic: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    transcription: "U'idhukuma bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah",
    russianTranscription: "Уизукума бикалиматиллях ит-таммати мин кулли шайтанин ва хамматин ва мин кулли айнин ляммах",
    translation: "Защищаю вас совершенными словами Аллаха от всякого шайтана и ядовитого животного, и от всякого дурного глаза",
    reference: "Сахих Бухари. Дуа Пророка ﷺ за Хасана и Хусейна",
    category: "children",
    count: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // ЗНАНИЯ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "knowledge-1",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transcription: "Rabbi zidni 'ilma",
    russianTranscription: "Рабби зидни ильма",
    translation: "Господи, приумножь моё знание",
    reference: "Коран 20:114",
    category: "knowledge",
    count: 1,
  },
  {
    id: "knowledge-2",
    arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا",
    transcription: "Allahum-ma-nfa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma",
    russianTranscription: "Аллахумма-нфаъни бима аллямтани ва аллимни ма янфауни ва зидни ильма",
    translation: "О Аллах, дай мне пользу от того, чему Ты научил меня, научи меня тому, что принесёт мне пользу, и приумножь моё знание",
    reference: "Тирмизи",
    category: "knowledge",
    count: 1,
  },
  {
    id: "knowledge-3",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ وَمِنْ قَلْبٍ لَا يَخْشَعُ وَمِنْ نَفْسٍ لَا تَشْبَعُ وَمِنْ دَعْوَةٍ لَا يُسْتَجَابُ لَهَا",
    transcription: "Allahumma inni a'udhu bika min 'ilmin la yanfa'u wa min qalbin la yakhsha'u wa min nafsin la tashba'u wa min da'watin la yustajabu laha",
    russianTranscription: "Аллахумма инни аузу бика мин ильмин ля янфау ва мин кальбин ля йахшау ва мин нафсин ля ташбау ва мин даъватин ля йустаджабу ляха",
    translation: "О Аллах, я прибегаю к Тебе от бесполезного знания, от сердца, которое не смиряется, от души, которая не насыщается, и от мольбы, которая не принимается",
    reference: "Сахих Муслим",
    category: "knowledge",
    count: 1,
  },

  // ─── Трудности ───
  {
    id: "hardship-1",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    transcription: "Hasbunallahu wa ni'mal-wakil",
    russianTranscription: "Хасбуналлаху ва ниъмаль-вакиль",
    translation: "Достаточен нам Аллах, и прекрасен Он как Попечитель",
    reference: "Коран 3:173",
    category: "hardship",
    count: 7,
  },
  {
    id: "hardship-2",
    arabic: "لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    transcription: "La ilaha illa Anta Subhanaka inni kuntu minaz-zalimin",
    russianTranscription: "Ля иляха илля Анта Субханака инни кунту миназ-залимин",
    translation: "Нет божества, кроме Тебя. Пречист Ты! Воистину, я был из числа несправедливых",
    reference: "Дуа Юнуса, Коран 21:87",
    category: "hardship",
    count: 3,
  },
  {
    id: "hardship-3",
    arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
    transcription: "Allahumma la sahla illa ma ja'altahu sahlan wa anta taj'alul-hazna idha shi'ta sahla",
    russianTranscription: "Аллахумма ля сахля илля ма джаальтаху сахлян ва анта таджъалюль-хазна иза шиъта сахлян",
    translation: "О Аллах, нет лёгкости кроме той, что Ты сделал лёгкой, и Ты делаешь печаль лёгкой, когда пожелаешь",
    reference: "Ибн Хиббан",
    category: "hardship",
    count: 1,
  },

  // ─── Путешествие ───
  {
    id: "travel-1",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ",
    transcription: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun",
    russianTranscription: "Субханаль-лязи саххара ляна хаза ва ма кунна ляху мукринин ва инна иля Раббина лямункалибун",
    translation: "Пречист Тот, Кто подчинил нам это, ведь сами мы не смогли бы это сделать. И, воистину, мы вернёмся к нашему Господу",
    reference: "Коран 43:13-14",
    category: "travel",
    count: 1,
  },
  {
    id: "travel-2",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى",
    transcription: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa wa minal-'amali ma tarda",
    russianTranscription: "Аллахумма инна насъалюка фи сафарина хазаль-бирра ват-таква ва миналь-амали ма тарда",
    translation: "О Аллах, мы просим Тебя в этом путешествии благочестия, богобоязненности и деяний, которыми Ты доволен",
    reference: "Сахих Муслим",
    category: "travel",
    count: 1,
  },

  // ─── Еда ───
  {
    id: "food-1",
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    transcription: "Bismillahi wa 'ala barakatillah",
    russianTranscription: "Бисмилляхи ва аля баракатиллях",
    translation: "С именем Аллаха и с благословением Аллаха",
    reference: "Абу Дауд",
    category: "food",
    count: 1,
  },
  {
    id: "food-2",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transcription: "Alhamdulillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    russianTranscription: "Альхамдулилляхиль-лязи атъамани хаза ва разакниихи мин гайри хаулин минни ва ля кувватин",
    translation: "Хвала Аллаху, Который накормил меня этим и наделил меня этим без усилий и мощи с моей стороны",
    reference: "Абу Дауд, Тирмизи",
    category: "food",
    count: 1,
  },

  // ─── Родители ───
  {
    id: "parents-1",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transcription: "Rabbir-hamhuma kama rabbayani saghira",
    russianTranscription: "Раббир-хамхума кама раббаяни сагыра",
    translation: "Господи! Помилуй их, как они растили меня ребёнком",
    reference: "Коран 17:24",
    category: "parents",
    count: 3,
  },
  {
    id: "parents-2",
    arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    transcription: "Rabbana-ghfir li wa liwalidayya wa lil-mu'minina yawma yaqumul-hisab",
    russianTranscription: "Раббанагфир ли ва ливалидаййа ва лиль-муъминина йауыма якумуль-хисаб",
    translation: "Господь наш! Прости меня, моих родителей и верующих в тот День, когда наступит расчёт",
    reference: "Коран 14:41",
    category: "parents",
    count: 1,
  },

  // ─── Знание ───
  {
    id: "knowledge-1",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transcription: "Rabbi zidni 'ilma",
    russianTranscription: "Рабби зидни ильма",
    translation: "Господи, приумножь моё знание",
    reference: "Коран 20:114",
    category: "knowledge",
    count: 3,
  },
  {
    id: "knowledge-2",
    arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا",
    transcription: "Allahumma-nfa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma",
    russianTranscription: "Аллахумманфаъни бима аллямтани ва аллимни ма янфауни ва зидни ильма",
    translation: "О Аллах, сделай полезным для меня то, чему Ты научил меня, научи меня тому, что принесёт мне пользу, и прибавь мне знания",
    reference: "Тирмизи",
    category: "knowledge",
    count: 1,
  },

  // ─── После намаза ───
  {
    id: "after-prayer-1",
    arabic: "أَسْتَغْفِرُ اللَّهَ أَسْتَغْفِرُ اللَّهَ أَسْتَغْفِرُ اللَّهَ",
    transcription: "Astaghfirullah, Astaghfirullah, Astaghfirullah",
    russianTranscription: "Астагфируллах, Астагфируллах, Астагфируллах",
    translation: "Прошу прощения у Аллаха (3 раза)",
    reference: "Сахих Муслим",
    category: "after_prayer",
    count: 3,
  },
  {
    id: "after-prayer-2",
    arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    transcription: "Allahumma antas-Salamu wa minkas-salam tabarakta ya Dhal-Jalali wal-Ikram",
    russianTranscription: "Аллахумма антас-Саляму ва минкас-салям табаракта йа Заль-Джаляли валь-Икрам",
    translation: "О Аллах, Ты — Мир, и от Тебя мир. Благословен Ты, о Обладатель величия и почёта",
    reference: "Сахих Муслим",
    category: "after_prayer",
    count: 1,
  },
];

// ═══════════════════════════════════════════════════════════════
// АЗКАРЫ (Поминания) - расширенный список
// ═══════════════════════════════════════════════════════════════

export const EXTENDED_ADHKAR: DhikrItem[] = [
  // ═══════════════════════════════════════════════════════════════
  // ОСНОВНЫЕ ЗИКРЫ (после намаза)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "tasbih-1",
    title: "Тасбих",
    arabic: "سُبْحَانَ اللَّهِ",
    transcription: "Subhanallah",
    russianTranscription: "СубханАллах",
    translation: "Пречист Аллах (Слава Аллаху)",
    reference: "После каждого намаза",
    count: 33,
    category: "after_prayer",
  },
  {
    id: "tahmid-1",
    title: "Тахмид",
    arabic: "الْحَمْدُ لِلَّهِ",
    transcription: "Alhamdulillah",
    russianTranscription: "Альхамдулиллях",
    translation: "Хвала Аллаху",
    reference: "После каждого намаза",
    count: 33,
    category: "after_prayer",
  },
  {
    id: "takbir-1",
    title: "Такбир",
    arabic: "اللَّهُ أَكْبَرُ",
    transcription: "Allahu Akbar",
    russianTranscription: "Аллаху Акбар",
    translation: "Аллах Велик",
    reference: "После каждого намаза",
    count: 34,
    category: "after_prayer",
  },
  {
    id: "tahlil-1",
    title: "Тахлиль",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transcription: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa 'ala kulli shay'in qadir",
    russianTranscription: "Ля иляха илляллаху вахдаху ля шарика лях, ляхуль-мульку ва ляхуль-хамд, ва хува аля кулли шайин кадир",
    translation: "Нет божества, кроме Аллаха, Единого, у Которого нет сотоварища. Ему принадлежит власть и хвала, и Он над всякой вещью мощен",
    reference: "После каждого намаза, 10 раз. Сахих Бухари",
    count: 10,
    category: "after_prayer",
  },

  // ═══════════════════════════════════════════════════════════════
  // УТРЕННИЕ АЗКАРЫ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "morning-adhkar-1",
    title: "Аят аль-Курси утром",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    transcription: "Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhū sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard...",
    russianTranscription: "Аллаху ля иляха илля хуваль-Хаййюль-Каййюм. Ля таъхузуху синатун ва ля науm. Ляху ма фис-самавати ва ма филь-ард...",
    translation: "Аллах — нет божества, кроме Него, Живого, Вседержителя. Им не овладевает ни дремота, ни сон. Ему принадлежит всё, что на небесах и на земле...",
    reference: "Коран 2:255. Утром для защиты",
    count: 1,
    category: "morning",
  },
  {
    id: "morning-adhkar-2",
    title: "Сура Ихляс утром",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    transcription: "Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad",
    russianTranscription: "Куль хуваЛлаху ахад. Аллаху с-Самад. Лям йалид ва лям юляд. Ва лям йакун ляху куфуван ахад",
    translation: "Скажи: Он — Аллах Единый. Аллах Самодостаточный. Он не родил и не был рождён. И нет никого, равного Ему",
    reference: "Коран 112. Читать 3 раза утром",
    count: 3,
    category: "morning",
  },
  {
    id: "morning-adhkar-3",
    title: "Сура Фаляк утром",
    arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    transcription: "Qul a'udhu bi Rabbil-Falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad",
    russianTranscription: "Куль аузу бираббиль-фаляк. Мин шарри ма халяк. Ва мин шарри гасикин иза вакаб. Ва мин шаррин-наффасати филь-укад. Ва мин шарри хасидин иза хасад",
    translation: "Скажи: Прибегаю к Господу рассвета от зла того, что Он сотворил, от зла мрака, когда он наступает, от зла колдуний, дующих на узлы, от зла завистника, когда он завидует",
    reference: "Коран 113. Читать 3 раза утром",
    count: 3,
    category: "morning",
  },
  {
    id: "morning-adhkar-4",
    title: "Сура Нас утром",
    arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
    transcription: "Qul a'udhu bi Rabbin-Nas. Malikin-Nas. Ilahin-Nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas",
    russianTranscription: "Куль аузу бираббин-нас. Маликин-нас. Иляхин-нас. Мин шарриль-васвасиль-ханнас. Аллязи йувасвису фи судурин-нас. Миналь-джиннати ван-нас",
    translation: "Скажи: Прибегаю к Господу людей, Царю людей, Богу людей, от зла искусителя отступающего, который наущает в груди людей, из джиннов и людей",
    reference: "Коран 114. Читать 3 раза утром",
    count: 3,
    category: "morning",
  },
  {
    id: "morning-adhkar-5",
    title: "Господин истигфара (утро)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transcription: "Allahumma anta Rabbi la ilaha illa Anta khalaqtani wa ana 'abduka wa ana 'ala 'ahdika wa wa'dika mastata't. A'udhu bika min sharri ma sana't. Abu'u laka bini'matika 'alayya wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa Ant",
    russianTranscription: "Аллахумма анта Рабби ля иляха илля Анта халяктани ва ана абдука ва ана аля ахдика ва ваъдика мастатаът. Аузу бика мин шарри ма санаът. Абуу ляка биниъматика аляййа ва абуу бизанби фагфир ли фа иннаху ля ягфиру з-зунуба илля Ант",
    translation: "О Аллах, Ты — мой Господь, нет божества, кроме Тебя. Ты создал меня, и я — Твой раб. Я верен завету с Тобой и обещанию, насколько могу. Прибегаю к Тебе от зла того, что совершил. Признаю Твою милость ко мне и признаю свой грех. Прости меня, ведь никто не прощает грехи, кроме Тебя",
    reference: "Сайид аль-Истигфар. Сахих Бухари. Кто скажет утром и умрёт — войдёт в Рай",
    count: 1,
    category: "morning",
  },
  {
    id: "morning-adhkar-6",
    title: "Защита от зла утром",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transcription: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    russianTranscription: "Аузу бикалиматиллях ат-таммати мин шарри ма халяк",
    translation: "Прибегаю к совершенным словам Аллаха от зла того, что Он сотворил",
    reference: "Сахих Муслим. Защита от укуса ядовитых животных",
    count: 3,
    category: "morning",
  },
  {
    id: "morning-adhkar-7",
    title: "100 раз утром",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transcription: "Subhanallahi wa bihamdih",
    russianTranscription: "СубханАллахи ва бихамдих",
    translation: "Пречист Аллах и хвала Ему",
    reference: "Сахих Бухари. Прощаются грехи, даже если они подобны морской пене",
    count: 100,
    category: "morning",
  },

  // ═══════════════════════════════════════════════════════════════
  // ВЕЧЕРНИЕ АЗКАРЫ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "evening-adhkar-1",
    title: "Аят аль-Курси вечером",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...",
    transcription: "Allahu la ilaha illa Huwal-Hayyul-Qayyum...",
    russianTranscription: "Аллаху ля иляха илля хуваль-Хаййюль-Каййюм...",
    translation: "Аллах — нет божества, кроме Него, Живого, Вседержителя...",
    reference: "Коран 2:255. Вечером для защиты ночью",
    count: 1,
    category: "evening",
  },
  {
    id: "evening-adhkar-2",
    title: "Муаввизатайн вечером",
    arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ... قُلْ أَعُوذُ بِرَبِّ النَّاسِ...",
    transcription: "Qul a'udhu bi Rabbil-Falaq... Qul a'udhu bi Rabbin-Nas...",
    russianTranscription: "Куль аузу бираббиль-фаляк... Куль аузу бираббин-нас...",
    translation: "Суры Фаляк и Нас",
    reference: "Читать по 3 раза вечером. Сахих Муслим",
    count: 3,
    category: "evening",
  },
  {
    id: "evening-adhkar-3",
    title: "Господин истигфара (вечер)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ...",
    transcription: "Allahumma anta Rabbi la ilaha illa Anta...",
    russianTranscription: "Аллахумма анта Рабби ля иляха илля Анта...",
    translation: "О Аллах, Ты — мой Господь, нет божества, кроме Тебя...",
    reference: "Кто скажет вечером и умрёт ночью — войдёт в Рай",
    count: 1,
    category: "evening",
  },
  {
    id: "evening-adhkar-4",
    title: "100 раз вечером",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transcription: "Subhanallahi wa bihamdih",
    russianTranscription: "СубханАллахи ва бихамдих",
    translation: "Пречист Аллах и хвала Ему",
    reference: "Сахих Муслим",
    count: 100,
    category: "evening",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПЕРЕД СНОМ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sleep-adhkar-1",
    title: "Аят аль-Курси перед сном",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...",
    transcription: "Allahu la ilaha illa Huwal-Hayyul-Qayyum...",
    russianTranscription: "Аллаху ля иляха илля хуваль-Хаййюль-Каййюм...",
    translation: "Аллах — нет божества, кроме Него...",
    reference: "Ангел будет охранять всю ночь",
    count: 1,
    category: "sleep",
  },
  {
    id: "sleep-adhkar-2",
    title: "Последние аяты Бакары",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ...",
    transcription: "Amanar-Rasulu bima unzila ilayhi min Rabbihi wal-mu'minun...",
    russianTranscription: "Аманар-Расулу бима унзиля иляйхи мин Раббихи валь-муъминун...",
    translation: "Уверовал Посланник в то, что ниспослано ему от Господа, и верующие...",
    reference: "Коран 2:285-286. Достаточно для защиты ночью",
    count: 1,
    category: "sleep",
  },
  {
    id: "sleep-adhkar-3",
    title: "Сура Мульк перед сном",
    arabic: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ...",
    transcription: "Tabarakal-ladhi biyadihil-mulku wa huwa 'ala kulli shay'in qadir...",
    russianTranscription: "Табаракаль-лязи биядихиль-мульку ва хува аля кулли шайин кадир...",
    translation: "Благословен Тот, в Чьей Руке власть, и Он над всякой вещью мощен...",
    reference: "Коран 67. Защита от наказания могилы",
    count: 1,
    category: "sleep",
  },
  {
    id: "sleep-adhkar-4",
    title: "33-33-34 перед сном",
    arabic: "سُبْحَانَ اللَّهِ (33) الْحَمْدُ لِلَّهِ (33) اللَّهُ أَكْبَرُ (34)",
    transcription: "Subhanallah (33), Alhamdulillah (33), Allahu Akbar (34)",
    russianTranscription: "СубханАллах (33), Альхамдулиллях (33), Аллаху Акбар (34)",
    translation: "Пречист Аллах, Хвала Аллаху, Аллах Велик",
    reference: "Совет Пророка ﷺ Фатиме. Лучше слуги",
    count: 100,
    category: "sleep",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПРИ ВЫХОДЕ ИЗ ДОМА
  // ═══════════════════════════════════════════════════════════════
  {
    id: "leaving-home-1",
    title: "При выходе из дома",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transcription: "Bismillahi tawakkaltu 'alallah, la hawla wa la quwwata illa billah",
    russianTranscription: "Бисмилляхи таваккальту аляллах, ля хауля ва ля кувата илля биллях",
    translation: "С именем Аллаха, уповаю на Аллаха, нет силы и мощи, кроме как с Аллахом",
    reference: "Абу Дауд, Тирмизи. Будет направлен, защищён и охранён",
    count: 1,
    category: "daily",
  },
  {
    id: "leaving-home-2",
    title: "При выходе из дома (2)",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ أَوْ أَزِلَّ أَوْ أُزَلَّ أَوْ أَظْلِمَ أَوْ أُظْلَمَ أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَيَّ",
    transcription: "Allahumma inni a'udhu bika an adilla aw udalla aw azilla aw uzalla aw azlima aw uzlama aw ajhala aw yujhala 'alayya",
    russianTranscription: "Аллахумма инни аузу бика ан адылля ау удалля ау азилля ау узалля ау азлима ау узляма ау аджхаля ау йуджхаля аляййа",
    translation: "О Аллах, я прибегаю к Тебе от того, чтобы сбиться с пути или быть сбитым, оступиться или быть оступлённым, притеснять или быть притеснённым, поступить невежественно или чтобы со мной поступили невежественно",
    reference: "Абу Дауд, Тирмизи",
    count: 1,
    category: "daily",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПРИ ВХОДЕ В ДОМ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "entering-home-1",
    title: "При входе в дом",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا",
    transcription: "Bismillahi walajna wa bismillahi kharajna wa 'ala Rabbina tawakkalna",
    russianTranscription: "Бисмилляхи валяджна ва бисмилляхи хараджна ва аля Раббина таваккальна",
    translation: "С именем Аллаха мы вошли, с именем Аллаха мы вышли и на Господа нашего уповаем",
    reference: "Абу Дауд. Шайтан скажет: нет вам здесь ни ночлега, ни ужина",
    count: 1,
    category: "daily",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПРИ ВХОДЕ/ВЫХОДЕ ИЗ МЕЧЕТИ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "entering-mosque-1",
    title: "При входе в мечеть",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transcription: "Allahumma-ftah li abwaba rahmatik",
    russianTranscription: "Аллахуммафтах ли абваба рахматик",
    translation: "О Аллах, открой мне врата Твоей милости",
    reference: "Сахих Муслим",
    count: 1,
    category: "mosque",
  },
  {
    id: "leaving-mosque-1",
    title: "При выходе из мечети",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transcription: "Allahumma inni as'aluka min fadlik",
    russianTranscription: "Аллахумма инни асъалюка мин фадлик",
    translation: "О Аллах, я прошу Тебя из Твоей милости",
    reference: "Сахих Муслим",
    count: 1,
    category: "mosque",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПРИ ОДЕВАНИИ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "clothing-1",
    title: "При надевании одежды",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transcription: "Alhamdulillahil-ladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    russianTranscription: "Альхамдулилляхиль-лязи касани хаза ва разакниихи мин гайри хаулин минни ва ля кувва",
    translation: "Хвала Аллаху, Который одел меня в это и наделил меня этим без усилий и мощи с моей стороны",
    reference: "Абу Дауд, Тирмизи. Прощаются прошлые грехи",
    count: 1,
    category: "daily",
  },
  {
    id: "clothing-2",
    title: "При надевании новой одежды",
    arabic: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ أَسْأَلُكَ خَيْرَهُ وَخَيْرَ مَا صُنِعَ لَهُ وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ",
    transcription: "Allahumma lakal-hamdu Anta kasawtanihi as'aluka khayrahu wa khayra ma suni'a lahu wa a'udhu bika min sharrihi wa sharri ma suni'a lah",
    russianTranscription: "Аллахумма лякаль-хамду Анта касаутаниихи асъалюка хайраху ва хайра ма суниа ляху ва аузу бика мин шарриихи ва шарри ма суниа лях",
    translation: "О Аллах, хвала Тебе, Ты одел меня в это. Прошу Тебя о благе его и благе того, для чего оно сделано, и прибегаю к Тебе от зла его и зла того, для чего оно сделано",
    reference: "Абу Дауд, Тирмизи",
    count: 1,
    category: "daily",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ В ТУАЛЕТЕ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "toilet-enter-1",
    title: "При входе в туалет",
    arabic: "بِسْمِ اللَّهِ اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    transcription: "Bismillah. Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
    russianTranscription: "Бисмиллях. Аллахумма инни аузу бика миналь-хубуси валь-хабаис",
    translation: "С именем Аллаха. О Аллах, я прибегаю к Тебе от злых джиннов мужского и женского пола",
    reference: "Сахих Бухари, Муслим",
    count: 1,
    category: "daily",
  },
  {
    id: "toilet-exit-1",
    title: "При выходе из туалета",
    arabic: "غُفْرَانَكَ",
    transcription: "Ghufranaka",
    russianTranscription: "Гуфранак",
    translation: "Прошу Твоего прощения",
    reference: "Абу Дауд, Тирмизи",
    count: 1,
    category: "daily",
  },

  // ═══════════════════════════════════════════════════════════════
  // АЗКАРЫ ПРИ ВЗГЛЯДЕ В ЗЕРКАЛО
  // ═══════════════════════════════════════════════════════════════
  {
    id: "mirror-1",
    title: "При взгляде в зеркало",
    arabic: "اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
    transcription: "Allahumma kama hassanta khalqi fahassin khuluqi",
    russianTranscription: "Аллахумма кама хассанта халькы фахассин хулюкы",
    translation: "О Аллах, как Ты сделал прекрасным мой облик, сделай прекрасным и мой нрав",
    reference: "Муснад Ахмад",
    count: 1,
    category: "daily",
  },

  // ═══════════════════════════════════════════════════════════════
  // ОСНОВНЫЕ ФОРМЫ ЗИКРА
  // ═══════════════════════════════════════════════════════════════
  {
    id: "hawqala-1",
    title: "Хаукаля",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transcription: "La hawla wa la quwwata illa billah",
    russianTranscription: "Ля хауля ва ля кувата илля биллях",
    translation: "Нет силы и мощи, кроме как с Аллахом",
    reference: "Сокровище из сокровищ Рая. Сахих Бухари",
    count: 10,
    category: "general",
  },
  {
    id: "istighfar-1",
    title: "Истигфар краткий",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    transcription: "Astaghfirullah",
    russianTranscription: "Астагфируллах",
    translation: "Прошу прощения у Аллаха",
    reference: "Читать 100 раз в день",
    count: 100,
    category: "general",
  },
  {
    id: "istighfar-2",
    title: "Истигфар полный",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transcription: "Astaghfirullaha al-'Adhima alladhi la ilaha illa Huwal-Hayyul-Qayyumu wa atubu ilayh",
    russianTranscription: "Астагфируллахаль-Азыма аллязи ля иляха илля хуваль-Хаййюль-Каййюму ва атубу иляйх",
    translation: "Прошу прощения у Великого Аллаха, кроме Которого нет божества, Живого, Вседержителя, и каюсь перед Ним",
    reference: "Абу Дауд, Тирмизи. Прощаются грехи, даже если бежал с поля боя",
    count: 3,
    category: "general",
  },
  {
    id: "basmala-1",
    title: "Басмаля",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    transcription: "Bismillahir-Rahmanir-Rahim",
    russianTranscription: "Бисмилляхир-Рахманир-Рахим",
    translation: "Во имя Аллаха, Милостивого, Милосердного",
    reference: "Перед любым делом",
    count: 1,
    category: "general",
  },
  {
    id: "combined-1",
    title: "Слова, любимые Аллахом",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ",
    transcription: "Subhanallahi wa bihamdihi, Subhanallahil-'Azim",
    russianTranscription: "СубханАллахи ва бихамдихи, СубханАллахиль-Азым",
    translation: "Пречист Аллах и хвала Ему, Пречист Аллах Великий",
    reference: "Сахих Бухари. Два слова, лёгких на языке, тяжёлых на весах",
    count: 100,
    category: "general",
  },
  {
    id: "combined-2",
    title: "Четыре великих слова",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ",
    transcription: "Subhanallah wal-hamdulillah wa la ilaha illallah wallahu akbar",
    russianTranscription: "СубханАллах валь-хамдулиллях ва ля иляха илляллах ваЛлаху акбар",
    translation: "Пречист Аллах, хвала Аллаху, нет божества кроме Аллаха, и Аллах Велик",
    reference: "Сахих Муслим. Любимее всего мирского",
    count: 25,
    category: "general",
  },
  {
    id: "combined-3",
    title: "Лучший зикр",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ",
    transcription: "La ilaha illallah",
    russianTranscription: "Ля иляха илляллах",
    translation: "Нет божества, кроме Аллаха",
    reference: "Лучший зикр. Тирмизи",
    count: 100,
    category: "general",
  },
  {
    id: "combined-4",
    title: "Засаживание дерева в Раю",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transcription: "Subhanallah wal-hamdulillah wa la ilaha illallah wallahu akbar wa la hawla wa la quwwata illa billah",
    russianTranscription: "СубханАллах валь-хамдулиллях ва ля иляха илляллах ваЛлаху акбар ва ля хауля ва ля кувата илля биллях",
    translation: "Пречист Аллах, хвала Аллаху, нет божества кроме Аллаха, Аллах Велик, и нет силы и мощи, кроме как с Аллахом",
    reference: "За каждое слово засаживается дерево в Раю. Тирмизи",
    count: 10,
    category: "general",
  },
  {
    id: "combined-2",
    title: "Четыре великих слова",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ",
    transcription: "Subhanallah wal-hamdulillah wa la ilaha illallah wallahu akbar",
    russianTranscription: "СубханАллах валь-хамдулиллях ва ля иляха илляллах ваЛлаху акбар",
    translation: "Пречист Аллах, хвала Аллаху, нет божества кроме Аллаха, и Аллах Велик",
    count: 25,
    category: "combined",
  },
];

// ═══════════════════════════════════════════════════════════════
// САЛАВАТЫ (Благословения пророку ﷺ)
// ═══════════════════════════════════════════════════════════════

export const EXTENDED_SALAWAT: DhikrItem[] = [
  {
    id: "salawat-1",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ",
    transcription: "Allahumma salli 'ala Muhammad",
    russianTranscription: "Аллахумма салли аля Мухаммад",
    translation: "О Аллах, благослови Мухаммада",
    reference: "Краткая форма",
    count: 10,
    category: "salawat",
  },
  {
    id: "salawat-2",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    transcription: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
    russianTranscription: "Аллахумма салли аля Мухаммадин ва аля али Мухаммад",
    translation: "О Аллах, благослови Мухаммада и семейство Мухаммада",
    reference: "Базовая форма",
    count: 10,
    category: "salawat",
  },
  {
    id: "salawat-ibrahimiyya",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transcription: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad kama sallayta 'ala Ibrahima wa 'ala ali Ibrahim innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammad kama barakta 'ala Ibrahima wa 'ala ali Ibrahim innaka Hamidun Majid",
    russianTranscription: "Аллахумма салли аля Мухаммадин ва аля али Мухаммад кама салляйта аля Ибрахима ва аля али Ибрахим иннака Хамидун Маджид. Аллахумма барик аля Мухаммадин ва аля али Мухаммад кама баракта аля Ибрахима ва аля али Ибрахим иннака Хамидун Маджид",
    translation: "О Аллах, благослови Мухаммада и семейство Мухаммада, как благословил Ибрахима и семейство Ибрахима. Воистину, Ты — Достохвальный, Славный. О Аллах, пошли благословение Мухаммаду и семейству Мухаммада, как послал благословение Ибрахиму и семейству Ибрахима. Воистину, Ты — Достохвальный, Славный",
    reference: "Салават Ибрахимийя (в тасаххуде)",
    count: 1,
    category: "salawat",
  },
  {
    id: "salawat-3",
    arabic: "صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
    transcription: "Sallallahu 'alayhi wa sallam",
    russianTranscription: "Саллаллаху алейхи ва саллям",
    translation: "Да благословит его Аллах и приветствует",
    reference: "Традиционная форма при упоминании Пророка ﷺ",
    count: 10,
    category: "salawat",
  },
];

// ═══════════════════════════════════════════════════════════════
// КАЛИМЫ (Формулы веры)
// ═══════════════════════════════════════════════════════════════

export const EXTENDED_KALIMAS: DhikrItem[] = [
  {
    id: "kalima-tayyiba",
    title: "Калима Тайиба (Слово чистоты)",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ مُحَمَّدٌ رَسُولُ اللَّهِ",
    transcription: "La ilaha illallah Muhammadur Rasulullah",
    russianTranscription: "Ля иляха илляллах Мухаммадур Расулюллах",
    translation: "Нет божества, кроме Аллаха, Мухаммад — Посланник Аллаха",
    reference: "Первая калима",
    category: "kalima",
  },
  {
    id: "kalima-shahada",
    title: "Калима Шахада (Свидетельство)",
    arabic: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    transcription: "Ashhadu an la ilaha illallah wa ashhadu anna Muhammadan 'abduhu wa rasuluh",
    russianTranscription: "Ашхаду ан ля иляха илляллах ва ашхаду анна Мухаммадан абдуху ва расулюх",
    translation: "Свидетельствую, что нет божества, кроме Аллаха, и свидетельствую, что Мухаммад — Его раб и Посланник",
    reference: "Вторая калима",
    category: "kalima",
  },
  {
    id: "kalima-tamjid",
    title: "Калима Тамджид (Слово величия)",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ",
    transcription: "Subhanallahi wal-hamdulillahi wa la ilaha illallahu wallahu akbar wa la hawla wa la quwwata illa billahil-'Aliyyil-'Azim",
    russianTranscription: "СубханАллахи валь-хамдулиллях ва ля иляха илляллаху ваЛлаху акбар ва ля хауля ва ля кувата илля билляхиль-Алийиль-Азым",
    translation: "Пречист Аллах, хвала Аллаху, нет божества кроме Аллаха, Аллах Велик, и нет силы и мощи кроме как от Аллаха Высочайшего, Великого",
    reference: "Третья калима",
    category: "kalima",
  },
  {
    id: "kalima-tawhid",
    title: "Калима Таухид (Слово единобожия)",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لَا يَمُوتُ أَبَدًا أَبَدًا ذُو الْجَلَالِ وَالْإِكْرَامِ بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transcription: "La ilaha illallahu wahdahu la sharika lahu lahul-mulku wa lahul-hamdu yuhyi wa yumitu wa huwa hayyun la yamutu abadan abada dhul-jalali wal-ikram biyadihil-khayru wa huwa 'ala kulli shay'in qadir",
    russianTranscription: "Ля иляха илляллаху вахдаху ля шарика ляху ляхуль-мульку ва ляхуль-хамду юхьи ва юмиту ва хува хаййун ля ямуту абадан абада зуль-джаляли валь-икрам биядихиль-хайру ва хува аля кулли шайин кадир",
    translation: "Нет божества, кроме Аллаха, Единого, у Которого нет сотоварища. Ему принадлежит власть и хвала. Он оживляет и умерщвляет. Он — Живой, Который не умрёт никогда. Обладатель величия и почёта. В Его руке благо, и Он над всякой вещью мощен",
    reference: "Четвёртая калима",
    category: "kalima",
  },
  {
    id: "kalima-astaghfar",
    title: "Калима Истигфар (Слово покаяния)",
    arabic: "أَسْتَغْفِرُ اللَّهَ رَبِّي مِنْ كُلِّ ذَنْبٍ أَذْنَبْتُهُ عَمْدًا أَوْ خَطَأً سِرًّا أَوْ عَلَانِيَةً وَأَتُوبُ إِلَيْهِ مِنَ الذَّنْبِ الَّذِي أَعْلَمُ وَمِنَ الذَّنْبِ الَّذِي لَا أَعْلَمُ إِنَّكَ أَنْتَ عَلَّامُ الْغُيُوبِ وَسَتَّارُ الْعُيُوبِ وَغَفَّارُ الذُّنُوبِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ",
    transcription: "Astaghfirullaha Rabbi min kulli dhanbin adhnabtuhu 'amdan aw khata'an sirran aw 'alaniyatan wa atubu ilayhi minadh-dhanbil-ladhi a'lamu wa minadh-dhanbil-ladhi la a'lamu innaka anta 'Allamul-ghuyubi wa Sattarul-'uyubi wa Ghaffarudh-dhunubi wa la hawla wa la quwwata illa billahil-'Aliyyil-'Azim",
    russianTranscription: "Астагфируллаха Рабби мин кулли занбин азнабтуху амдан ау хатаан сирран ау аланиятан ва атубу иляйхи миназ-занбиль-лязи аъляму ва миназ-занбиль-лязи ля аъляму иннака анта Аллямуль-гуйуби ва Саттаруль-уйуби ва Гаффаруз-зунуби ва ля хауля ва ля кувата илля билляхиль-Алийиль-Азым",
    translation: "Прошу прощения у Аллаха, моего Господа, за каждый грех, который я совершил намеренно или по ошибке, тайно или явно. И каюсь перед Ним от греха, который знаю, и от греха, который не знаю. Воистину, Ты — Знающий сокровенное, Скрывающий недостатки, Прощающий грехи. И нет силы и мощи, кроме как от Аллаха Высочайшего, Великого",
    reference: "Пятая калима",
    category: "kalima",
  },
  {
    id: "kalima-radde-kufr",
    title: "Калима Радде Куфр (Отвержение неверия)",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ أَنْ أُشْرِكَ بِكَ شَيْئًا وَأَنَا أَعْلَمُ وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ إِنَّكَ أَنْتَ عَلَّامُ الْغُيُوبِ",
    transcription: "Allahumma inni a'udhu bika min an ushrika bika shay'an wa ana a'lamu wa astaghfiruka lima la a'lamu innaka anta 'Allamul-ghuyub",
    russianTranscription: "Аллахумма инни аузу бика мин ан ушрика бика шайан ва ана аъляму ва астагфирука лима ля аъляму иннака анта Алляmuль-гуйуб",
    translation: "О Аллах, я прибегаю к Тебе от того, чтобы придавать Тебе сотоварищей сознательно, и прошу у Тебя прощения за то, о чём не знаю. Воистину, Ты — Знающий сокровенное",
    reference: "Шестая калима",
    category: "kalima",
  },
];

// Экспорт всех категорий
export const DUA_CATEGORIES = [
  { id: "morning", name: "Утренние дуа", icon: "🌅" },
  { id: "evening", name: "Вечерние дуа", icon: "🌙" },
  { id: "sleep", name: "Перед сном", icon: "😴" },
  { id: "protection", name: "Защита", icon: "🛡️" },
  { id: "repentance", name: "Покаяние", icon: "🤲" },
  { id: "gratitude", name: "Благодарность", icon: "❤️" },
  { id: "health", name: "Здоровье", icon: "💚" },
  { id: "rizq", name: "Ризк и богатство", icon: "💰" },
  { id: "family", name: "Семья и брак", icon: "👨‍👩‍👧" },
  { id: "children", name: "Дети", icon: "👶" },
  { id: "knowledge", name: "Знание", icon: "📚" },
  { id: "hardship", name: "В трудности", icon: "💪" },
  { id: "travel", name: "Путешествие", icon: "✈️" },
  { id: "food", name: "Еда", icon: "🍽️" },
  { id: "parents", name: "Родители", icon: "👨‍👩‍👦" },
  { id: "after_prayer", name: "После намаза", icon: "🕌" },
];

// Количество дуа по категориям
export const getDuaCountByCategory = (category: string): number => {
  return EXTENDED_DUAS.filter(d => d.category === category).length;
};

export const ADHKAR_CATEGORIES = [
  { id: "after_prayer", name: "После намаза", icon: "🕌" },
  { id: "morning", name: "Утренние азкары", icon: "🌅" },
  { id: "evening", name: "Вечерние азкары", icon: "🌙" },
  { id: "sleep", name: "Перед сном", icon: "😴" },
  { id: "daily", name: "Повседневные", icon: "🏠" },
  { id: "mosque", name: "В мечети", icon: "🕋" },
  { id: "general", name: "Общие зикры", icon: "📿" },
];

// Сколько азкаров в каждой категории
export const getAdhkarCountByCategory = (category: string): number => {
  return EXTENDED_ADHKAR.filter(a => a.category === category).length;
};

