// Полные данные Корана: 114 сур с информацией
// Источник: https://bot.e-replika.ru/docs

export interface SurahInfo {
  id: string;
  number: number;
  nameArabic: string;
  nameTransliteration: string;
  name: string; // Русское название
  englishName: string;
  revelationType: "meccan" | "medinan";
  versesCount: number;
  description?: string;
}

// Все 114 сур Корана
export const ALL_SURAHS: SurahInfo[] = [
  { id: "surah-1", number: 1, nameArabic: "الفاتحة", nameTransliteration: "Al-Fatiha", name: "Открывающая", englishName: "The Opening", revelationType: "meccan", versesCount: 7 },
  { id: "surah-2", number: 2, nameArabic: "البقرة", nameTransliteration: "Al-Baqara", name: "Корова", englishName: "The Cow", revelationType: "medinan", versesCount: 286 },
  { id: "surah-3", number: 3, nameArabic: "آل عمران", nameTransliteration: "Ali 'Imran", name: "Семейство Имрана", englishName: "Family of Imran", revelationType: "medinan", versesCount: 200 },
  { id: "surah-4", number: 4, nameArabic: "النساء", nameTransliteration: "An-Nisa", name: "Женщины", englishName: "The Women", revelationType: "medinan", versesCount: 176 },
  { id: "surah-5", number: 5, nameArabic: "المائدة", nameTransliteration: "Al-Ma'ida", name: "Трапеза", englishName: "The Table Spread", revelationType: "medinan", versesCount: 120 },
  { id: "surah-6", number: 6, nameArabic: "الأنعام", nameTransliteration: "Al-An'am", name: "Скот", englishName: "The Cattle", revelationType: "meccan", versesCount: 165 },
  { id: "surah-7", number: 7, nameArabic: "الأعراف", nameTransliteration: "Al-A'raf", name: "Преграды", englishName: "The Heights", revelationType: "meccan", versesCount: 206 },
  { id: "surah-8", number: 8, nameArabic: "الأنفال", nameTransliteration: "Al-Anfal", name: "Добыча", englishName: "The Spoils of War", revelationType: "medinan", versesCount: 75 },
  { id: "surah-9", number: 9, nameArabic: "التوبة", nameTransliteration: "At-Tawba", name: "Покаяние", englishName: "The Repentance", revelationType: "medinan", versesCount: 129 },
  { id: "surah-10", number: 10, nameArabic: "يونس", nameTransliteration: "Yunus", name: "Юнус", englishName: "Jonah", revelationType: "meccan", versesCount: 109 },
  { id: "surah-11", number: 11, nameArabic: "هود", nameTransliteration: "Hud", name: "Худ", englishName: "Hud", revelationType: "meccan", versesCount: 123 },
  { id: "surah-12", number: 12, nameArabic: "يوسف", nameTransliteration: "Yusuf", name: "Юсуф", englishName: "Joseph", revelationType: "meccan", versesCount: 111 },
  { id: "surah-13", number: 13, nameArabic: "الرعد", nameTransliteration: "Ar-Ra'd", name: "Гром", englishName: "The Thunder", revelationType: "medinan", versesCount: 43 },
  { id: "surah-14", number: 14, nameArabic: "إبراهيم", nameTransliteration: "Ibrahim", name: "Ибрахим", englishName: "Abraham", revelationType: "meccan", versesCount: 52 },
  { id: "surah-15", number: 15, nameArabic: "الحجر", nameTransliteration: "Al-Hijr", name: "Хиджр", englishName: "The Rocky Tract", revelationType: "meccan", versesCount: 99 },
  { id: "surah-16", number: 16, nameArabic: "النحل", nameTransliteration: "An-Nahl", name: "Пчёлы", englishName: "The Bee", revelationType: "meccan", versesCount: 128 },
  { id: "surah-17", number: 17, nameArabic: "الإسراء", nameTransliteration: "Al-Isra", name: "Ночной перенос", englishName: "The Night Journey", revelationType: "meccan", versesCount: 111 },
  { id: "surah-18", number: 18, nameArabic: "الكهف", nameTransliteration: "Al-Kahf", name: "Пещера", englishName: "The Cave", revelationType: "meccan", versesCount: 110 },
  { id: "surah-19", number: 19, nameArabic: "مريم", nameTransliteration: "Maryam", name: "Марьям", englishName: "Mary", revelationType: "meccan", versesCount: 98 },
  { id: "surah-20", number: 20, nameArabic: "طه", nameTransliteration: "Ta-Ha", name: "Та Ха", englishName: "Ta-Ha", revelationType: "meccan", versesCount: 135 },
  { id: "surah-21", number: 21, nameArabic: "الأنبياء", nameTransliteration: "Al-Anbiya", name: "Пророки", englishName: "The Prophets", revelationType: "meccan", versesCount: 112 },
  { id: "surah-22", number: 22, nameArabic: "الحج", nameTransliteration: "Al-Hajj", name: "Хадж", englishName: "The Pilgrimage", revelationType: "medinan", versesCount: 78 },
  { id: "surah-23", number: 23, nameArabic: "المؤمنون", nameTransliteration: "Al-Mu'minun", name: "Верующие", englishName: "The Believers", revelationType: "meccan", versesCount: 118 },
  { id: "surah-24", number: 24, nameArabic: "النور", nameTransliteration: "An-Nur", name: "Свет", englishName: "The Light", revelationType: "medinan", versesCount: 64 },
  { id: "surah-25", number: 25, nameArabic: "الفرقان", nameTransliteration: "Al-Furqan", name: "Различение", englishName: "The Criterion", revelationType: "meccan", versesCount: 77 },
  { id: "surah-26", number: 26, nameArabic: "الشعراء", nameTransliteration: "Ash-Shu'ara", name: "Поэты", englishName: "The Poets", revelationType: "meccan", versesCount: 227 },
  { id: "surah-27", number: 27, nameArabic: "النمل", nameTransliteration: "An-Naml", name: "Муравьи", englishName: "The Ant", revelationType: "meccan", versesCount: 93 },
  { id: "surah-28", number: 28, nameArabic: "القصص", nameTransliteration: "Al-Qasas", name: "Рассказ", englishName: "The Stories", revelationType: "meccan", versesCount: 88 },
  { id: "surah-29", number: 29, nameArabic: "العنكبوت", nameTransliteration: "Al-Ankabut", name: "Паук", englishName: "The Spider", revelationType: "meccan", versesCount: 69 },
  { id: "surah-30", number: 30, nameArabic: "الروم", nameTransliteration: "Ar-Rum", name: "Римляне", englishName: "The Romans", revelationType: "meccan", versesCount: 60 },
  { id: "surah-31", number: 31, nameArabic: "لقمان", nameTransliteration: "Luqman", name: "Лукман", englishName: "Luqman", revelationType: "meccan", versesCount: 34 },
  { id: "surah-32", number: 32, nameArabic: "السجدة", nameTransliteration: "As-Sajda", name: "Поклон", englishName: "The Prostration", revelationType: "meccan", versesCount: 30 },
  { id: "surah-33", number: 33, nameArabic: "الأحزاب", nameTransliteration: "Al-Ahzab", name: "Союзники", englishName: "The Combined Forces", revelationType: "medinan", versesCount: 73 },
  { id: "surah-34", number: 34, nameArabic: "سبأ", nameTransliteration: "Saba", name: "Саба", englishName: "Sheba", revelationType: "meccan", versesCount: 54 },
  { id: "surah-35", number: 35, nameArabic: "فاطر", nameTransliteration: "Fatir", name: "Творец", englishName: "Originator", revelationType: "meccan", versesCount: 45 },
  { id: "surah-36", number: 36, nameArabic: "يس", nameTransliteration: "Ya-Sin", name: "Йа Син", englishName: "Ya-Sin", revelationType: "meccan", versesCount: 83 },
  { id: "surah-37", number: 37, nameArabic: "الصافات", nameTransliteration: "As-Saffat", name: "Выстроившиеся в ряды", englishName: "Those Who Set The Ranks", revelationType: "meccan", versesCount: 182 },
  { id: "surah-38", number: 38, nameArabic: "ص", nameTransliteration: "Sad", name: "Сад", englishName: "The Letter Sad", revelationType: "meccan", versesCount: 88 },
  { id: "surah-39", number: 39, nameArabic: "الزمر", nameTransliteration: "Az-Zumar", name: "Толпы", englishName: "The Troops", revelationType: "meccan", versesCount: 75 },
  { id: "surah-40", number: 40, nameArabic: "غافر", nameTransliteration: "Ghafir", name: "Прощающий", englishName: "The Forgiver", revelationType: "meccan", versesCount: 85 },
  { id: "surah-41", number: 41, nameArabic: "فصلت", nameTransliteration: "Fussilat", name: "Разъяснены", englishName: "Explained in Detail", revelationType: "meccan", versesCount: 54 },
  { id: "surah-42", number: 42, nameArabic: "الشورى", nameTransliteration: "Ash-Shura", name: "Совет", englishName: "The Consultation", revelationType: "meccan", versesCount: 53 },
  { id: "surah-43", number: 43, nameArabic: "الزخرف", nameTransliteration: "Az-Zukhruf", name: "Украшения", englishName: "The Ornaments of Gold", revelationType: "meccan", versesCount: 89 },
  { id: "surah-44", number: 44, nameArabic: "الدخان", nameTransliteration: "Ad-Dukhan", name: "Дым", englishName: "The Smoke", revelationType: "meccan", versesCount: 59 },
  { id: "surah-45", number: 45, nameArabic: "الجاثية", nameTransliteration: "Al-Jathiya", name: "Коленопреклонённые", englishName: "The Crouching", revelationType: "meccan", versesCount: 37 },
  { id: "surah-46", number: 46, nameArabic: "الأحقاف", nameTransliteration: "Al-Ahqaf", name: "Барханы", englishName: "The Wind-curved Sandhills", revelationType: "meccan", versesCount: 35 },
  { id: "surah-47", number: 47, nameArabic: "محمد", nameTransliteration: "Muhammad", name: "Мухаммад", englishName: "Muhammad", revelationType: "medinan", versesCount: 38 },
  { id: "surah-48", number: 48, nameArabic: "الفتح", nameTransliteration: "Al-Fath", name: "Победа", englishName: "The Victory", revelationType: "medinan", versesCount: 29 },
  { id: "surah-49", number: 49, nameArabic: "الحجرات", nameTransliteration: "Al-Hujurat", name: "Комнаты", englishName: "The Rooms", revelationType: "medinan", versesCount: 18 },
  { id: "surah-50", number: 50, nameArabic: "ق", nameTransliteration: "Qaf", name: "Каф", englishName: "The Letter Qaf", revelationType: "meccan", versesCount: 45 },
  { id: "surah-51", number: 51, nameArabic: "الذاريات", nameTransliteration: "Adh-Dhariyat", name: "Рассеивающие", englishName: "The Winnowing Winds", revelationType: "meccan", versesCount: 60 },
  { id: "surah-52", number: 52, nameArabic: "الطور", nameTransliteration: "At-Tur", name: "Гора", englishName: "The Mount", revelationType: "meccan", versesCount: 49 },
  { id: "surah-53", number: 53, nameArabic: "النجم", nameTransliteration: "An-Najm", name: "Звезда", englishName: "The Star", revelationType: "meccan", versesCount: 62 },
  { id: "surah-54", number: 54, nameArabic: "القمر", nameTransliteration: "Al-Qamar", name: "Луна", englishName: "The Moon", revelationType: "meccan", versesCount: 55 },
  { id: "surah-55", number: 55, nameArabic: "الرحمن", nameTransliteration: "Ar-Rahman", name: "Милостивый", englishName: "The Beneficent", revelationType: "medinan", versesCount: 78 },
  { id: "surah-56", number: 56, nameArabic: "الواقعة", nameTransliteration: "Al-Waqi'a", name: "Событие", englishName: "The Inevitable", revelationType: "meccan", versesCount: 96 },
  { id: "surah-57", number: 57, nameArabic: "الحديد", nameTransliteration: "Al-Hadid", name: "Железо", englishName: "The Iron", revelationType: "medinan", versesCount: 29 },
  { id: "surah-58", number: 58, nameArabic: "المجادلة", nameTransliteration: "Al-Mujadila", name: "Препирающаяся", englishName: "The Pleading Woman", revelationType: "medinan", versesCount: 22 },
  { id: "surah-59", number: 59, nameArabic: "الحشر", nameTransliteration: "Al-Hashr", name: "Сбор", englishName: "The Exile", revelationType: "medinan", versesCount: 24 },
  { id: "surah-60", number: 60, nameArabic: "الممتحنة", nameTransliteration: "Al-Mumtahana", name: "Испытуемая", englishName: "She That Is To Be Examined", revelationType: "medinan", versesCount: 13 },
  { id: "surah-61", number: 61, nameArabic: "الصف", nameTransliteration: "As-Saff", name: "Ряды", englishName: "The Ranks", revelationType: "medinan", versesCount: 14 },
  { id: "surah-62", number: 62, nameArabic: "الجمعة", nameTransliteration: "Al-Jumu'a", name: "Пятница", englishName: "The Congregation, Friday", revelationType: "medinan", versesCount: 11 },
  { id: "surah-63", number: 63, nameArabic: "المنافقون", nameTransliteration: "Al-Munafiqun", name: "Лицемеры", englishName: "The Hypocrites", revelationType: "medinan", versesCount: 11 },
  { id: "surah-64", number: 64, nameArabic: "التغابن", nameTransliteration: "At-Taghabun", name: "Взаимное обманывание", englishName: "The Mutual Disillusion", revelationType: "medinan", versesCount: 18 },
  { id: "surah-65", number: 65, nameArabic: "الطلاق", nameTransliteration: "At-Talaq", name: "Развод", englishName: "The Divorce", revelationType: "medinan", versesCount: 12 },
  { id: "surah-66", number: 66, nameArabic: "التحريم", nameTransliteration: "At-Tahrim", name: "Запрещение", englishName: "The Prohibition", revelationType: "medinan", versesCount: 12 },
  { id: "surah-67", number: 67, nameArabic: "الملك", nameTransliteration: "Al-Mulk", name: "Власть", englishName: "The Sovereignty", revelationType: "meccan", versesCount: 30 },
  { id: "surah-68", number: 68, nameArabic: "القلم", nameTransliteration: "Al-Qalam", name: "Письменная трость", englishName: "The Pen", revelationType: "meccan", versesCount: 52 },
  { id: "surah-69", number: 69, nameArabic: "الحاقة", nameTransliteration: "Al-Haqqa", name: "Неизбежное", englishName: "The Reality", revelationType: "meccan", versesCount: 52 },
  { id: "surah-70", number: 70, nameArabic: "المعارج", nameTransliteration: "Al-Ma'arij", name: "Ступени", englishName: "The Ascending Stairways", revelationType: "meccan", versesCount: 44 },
  { id: "surah-71", number: 71, nameArabic: "نوح", nameTransliteration: "Nuh", name: "Нух", englishName: "Noah", revelationType: "meccan", versesCount: 28 },
  { id: "surah-72", number: 72, nameArabic: "الجن", nameTransliteration: "Al-Jinn", name: "Джинны", englishName: "The Jinn", revelationType: "meccan", versesCount: 28 },
  { id: "surah-73", number: 73, nameArabic: "المزمل", nameTransliteration: "Al-Muzzammil", name: "Закутавшийся", englishName: "The Enshrouded One", revelationType: "meccan", versesCount: 20 },
  { id: "surah-74", number: 74, nameArabic: "المدثر", nameTransliteration: "Al-Muddathir", name: "Завернувшийся", englishName: "The Cloaked One", revelationType: "meccan", versesCount: 56 },
  { id: "surah-75", number: 75, nameArabic: "القيامة", nameTransliteration: "Al-Qiyama", name: "Воскресение", englishName: "The Resurrection", revelationType: "meccan", versesCount: 40 },
  { id: "surah-76", number: 76, nameArabic: "الإنسان", nameTransliteration: "Al-Insan", name: "Человек", englishName: "The Man", revelationType: "medinan", versesCount: 31 },
  { id: "surah-77", number: 77, nameArabic: "المرسلات", nameTransliteration: "Al-Mursalat", name: "Посылаемые", englishName: "The Emissaries", revelationType: "meccan", versesCount: 50 },
  { id: "surah-78", number: 78, nameArabic: "النبأ", nameTransliteration: "An-Naba", name: "Весть", englishName: "The Tidings", revelationType: "meccan", versesCount: 40 },
  { id: "surah-79", number: 79, nameArabic: "النازعات", nameTransliteration: "An-Nazi'at", name: "Вырывающие", englishName: "Those Who Drag Forth", revelationType: "meccan", versesCount: 46 },
  { id: "surah-80", number: 80, nameArabic: "عبس", nameTransliteration: "Abasa", name: "Нахмурился", englishName: "He Frowned", revelationType: "meccan", versesCount: 42 },
  { id: "surah-81", number: 81, nameArabic: "التكوير", nameTransliteration: "At-Takwir", name: "Скручивание", englishName: "The Overthrowing", revelationType: "meccan", versesCount: 29 },
  { id: "surah-82", number: 82, nameArabic: "الانفطار", nameTransliteration: "Al-Infitar", name: "Раскалывание", englishName: "The Cleaving", revelationType: "meccan", versesCount: 19 },
  { id: "surah-83", number: 83, nameArabic: "المطففين", nameTransliteration: "Al-Mutaffifin", name: "Обвешивающие", englishName: "The Defrauding", revelationType: "meccan", versesCount: 36 },
  { id: "surah-84", number: 84, nameArabic: "الانشقاق", nameTransliteration: "Al-Inshiqaq", name: "Разверзнется", englishName: "The Sundering", revelationType: "meccan", versesCount: 25 },
  { id: "surah-85", number: 85, nameArabic: "البروج", nameTransliteration: "Al-Buruj", name: "Созвездия", englishName: "The Mansions of the Stars", revelationType: "meccan", versesCount: 22 },
  { id: "surah-86", number: 86, nameArabic: "الطارق", nameTransliteration: "At-Tariq", name: "Ночной путник", englishName: "The Morning Star", revelationType: "meccan", versesCount: 17 },
  { id: "surah-87", number: 87, nameArabic: "الأعلى", nameTransliteration: "Al-A'la", name: "Всевышний", englishName: "The Most High", revelationType: "meccan", versesCount: 19 },
  { id: "surah-88", number: 88, nameArabic: "الغاشية", nameTransliteration: "Al-Ghashiya", name: "Покрывающее", englishName: "The Overwhelming", revelationType: "meccan", versesCount: 26 },
  { id: "surah-89", number: 89, nameArabic: "الفجر", nameTransliteration: "Al-Fajr", name: "Заря", englishName: "The Dawn", revelationType: "meccan", versesCount: 30 },
  { id: "surah-90", number: 90, nameArabic: "البلد", nameTransliteration: "Al-Balad", name: "Город", englishName: "The City", revelationType: "meccan", versesCount: 20 },
  { id: "surah-91", number: 91, nameArabic: "الشمس", nameTransliteration: "Ash-Shams", name: "Солнце", englishName: "The Sun", revelationType: "meccan", versesCount: 15 },
  { id: "surah-92", number: 92, nameArabic: "الليل", nameTransliteration: "Al-Layl", name: "Ночь", englishName: "The Night", revelationType: "meccan", versesCount: 21 },
  { id: "surah-93", number: 93, nameArabic: "الضحى", nameTransliteration: "Ad-Duha", name: "Утро", englishName: "The Morning Hours", revelationType: "meccan", versesCount: 11 },
  { id: "surah-94", number: 94, nameArabic: "الشرح", nameTransliteration: "Ash-Sharh", name: "Раскрытие", englishName: "The Relief", revelationType: "meccan", versesCount: 8 },
  { id: "surah-95", number: 95, nameArabic: "التين", nameTransliteration: "At-Tin", name: "Смоковница", englishName: "The Fig", revelationType: "meccan", versesCount: 8 },
  { id: "surah-96", number: 96, nameArabic: "العلق", nameTransliteration: "Al-Alaq", name: "Сгусток", englishName: "The Clot", revelationType: "meccan", versesCount: 19 },
  { id: "surah-97", number: 97, nameArabic: "القدر", nameTransliteration: "Al-Qadr", name: "Предопределение", englishName: "The Power", revelationType: "meccan", versesCount: 5 },
  { id: "surah-98", number: 98, nameArabic: "البينة", nameTransliteration: "Al-Bayyina", name: "Ясное знамение", englishName: "The Clear Proof", revelationType: "medinan", versesCount: 8 },
  { id: "surah-99", number: 99, nameArabic: "الزلزلة", nameTransliteration: "Az-Zalzala", name: "Сотрясение", englishName: "The Earthquake", revelationType: "medinan", versesCount: 8 },
  { id: "surah-100", number: 100, nameArabic: "العاديات", nameTransliteration: "Al-Adiyat", name: "Скачущие", englishName: "The Coursers", revelationType: "meccan", versesCount: 11 },
  { id: "surah-101", number: 101, nameArabic: "القارعة", nameTransliteration: "Al-Qari'a", name: "Великое бедствие", englishName: "The Calamity", revelationType: "meccan", versesCount: 11 },
  { id: "surah-102", number: 102, nameArabic: "التكاثر", nameTransliteration: "At-Takathur", name: "Страсть к приумножению", englishName: "The Rivalry in World Increase", revelationType: "meccan", versesCount: 8 },
  { id: "surah-103", number: 103, nameArabic: "العصر", nameTransliteration: "Al-Asr", name: "Предвечернее время", englishName: "The Declining Day", revelationType: "meccan", versesCount: 3 },
  { id: "surah-104", number: 104, nameArabic: "الهمزة", nameTransliteration: "Al-Humaza", name: "Хулитель", englishName: "The Traducer", revelationType: "meccan", versesCount: 9 },
  { id: "surah-105", number: 105, nameArabic: "الفيل", nameTransliteration: "Al-Fil", name: "Слон", englishName: "The Elephant", revelationType: "meccan", versesCount: 5 },
  { id: "surah-106", number: 106, nameArabic: "قريش", nameTransliteration: "Quraysh", name: "Курайш", englishName: "Quraysh", revelationType: "meccan", versesCount: 4 },
  { id: "surah-107", number: 107, nameArabic: "الماعون", nameTransliteration: "Al-Ma'un", name: "Мелочь", englishName: "The Small Kindnesses", revelationType: "meccan", versesCount: 7 },
  { id: "surah-108", number: 108, nameArabic: "الكوثر", nameTransliteration: "Al-Kawthar", name: "Изобилие", englishName: "The Abundance", revelationType: "meccan", versesCount: 3 },
  { id: "surah-109", number: 109, nameArabic: "الكافرون", nameTransliteration: "Al-Kafirun", name: "Неверующие", englishName: "The Disbelievers", revelationType: "meccan", versesCount: 6 },
  { id: "surah-110", number: 110, nameArabic: "النصر", nameTransliteration: "An-Nasr", name: "Победа", englishName: "The Divine Support", revelationType: "medinan", versesCount: 3 },
  { id: "surah-111", number: 111, nameArabic: "المسد", nameTransliteration: "Al-Masad", name: "Пальмовые волокна", englishName: "The Palm Fiber", revelationType: "meccan", versesCount: 5 },
  { id: "surah-112", number: 112, nameArabic: "الإخلاص", nameTransliteration: "Al-Ikhlas", name: "Искренность", englishName: "The Sincerity", revelationType: "meccan", versesCount: 4 },
  { id: "surah-113", number: 113, nameArabic: "الفلق", nameTransliteration: "Al-Falaq", name: "Рассвет", englishName: "The Daybreak", revelationType: "meccan", versesCount: 5 },
  { id: "surah-114", number: 114, nameArabic: "الناس", nameTransliteration: "An-Nas", name: "Люди", englishName: "Mankind", revelationType: "meccan", versesCount: 6 },
];

// Функция получения суры по номеру
export const getSurahByNumber = (number: number): SurahInfo | undefined => {
  return ALL_SURAHS.find(s => s.number === number);
};

// Группировка сур по джузам (частям)
export const JUZ_INFO: { juz: number; startSurah: number; startAyah: number; name?: string }[] = [
  { juz: 1, startSurah: 1, startAyah: 1, name: "Алиф Лам Мим" },
  { juz: 2, startSurah: 2, startAyah: 142 },
  { juz: 3, startSurah: 2, startAyah: 253 },
  { juz: 4, startSurah: 3, startAyah: 93 },
  { juz: 5, startSurah: 4, startAyah: 24 },
  { juz: 6, startSurah: 4, startAyah: 148 },
  { juz: 7, startSurah: 5, startAyah: 82 },
  { juz: 8, startSurah: 6, startAyah: 111 },
  { juz: 9, startSurah: 7, startAyah: 88 },
  { juz: 10, startSurah: 8, startAyah: 41 },
  { juz: 11, startSurah: 9, startAyah: 93 },
  { juz: 12, startSurah: 11, startAyah: 6 },
  { juz: 13, startSurah: 12, startAyah: 53 },
  { juz: 14, startSurah: 15, startAyah: 1 },
  { juz: 15, startSurah: 17, startAyah: 1 },
  { juz: 16, startSurah: 18, startAyah: 75 },
  { juz: 17, startSurah: 21, startAyah: 1 },
  { juz: 18, startSurah: 23, startAyah: 1 },
  { juz: 19, startSurah: 25, startAyah: 21 },
  { juz: 20, startSurah: 27, startAyah: 56 },
  { juz: 21, startSurah: 29, startAyah: 46 },
  { juz: 22, startSurah: 33, startAyah: 31 },
  { juz: 23, startSurah: 36, startAyah: 22 },
  { juz: 24, startSurah: 39, startAyah: 32 },
  { juz: 25, startSurah: 41, startAyah: 47 },
  { juz: 26, startSurah: 46, startAyah: 1 },
  { juz: 27, startSurah: 51, startAyah: 31 },
  { juz: 28, startSurah: 58, startAyah: 1 },
  { juz: 29, startSurah: 67, startAyah: 1 },
  { juz: 30, startSurah: 78, startAyah: 1, name: "Амма" },
];

// Популярные суры для быстрого доступа
export const POPULAR_SURAHS = [1, 2, 18, 36, 55, 56, 67, 78, 112, 113, 114];

